name: deploy
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
        
    - uses: actions/checkout@v2
      
    - uses: golangci/golangci-lint-action@v2.5.2
      with:
          version: v1.41.1
